// Central place for every Lucide icon used across the app. Every icon used anywhere in
// the app is registered here once via pick() — components import LucideIconModule and
// reference icons by kebab-case name string (e.g. name="chevron-up"), so no file needs to
// import individual icon objects from 'lucide-angular' directly.
import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  Mail,
  Phone,
  MapPin,
  Globe,
  Download,
  Trash2,
  Link,
  Camera,
  Bold,
  Italic,
  Underline,
  ListOrdered,
  List,
  TextAlignStart,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  RemoveFormatting,
  House,
  ChevronUp,
  ChevronDown,
  Sparkles,
  CircleUser,
  CreditCard,
  Bell,
  LogOut,
  UserKey,
  LogIn,
  GripVertical,
  Eye,
  X,
  Pencil,
  EllipsisVertical,
  ArrowRight,
  Copy,
  Files,
  FileText,
  GraduationCap,
  Briefcase,
  FolderOpen,
  Award,
  Languages,
  Heart,
  BookOpen,
  Trophy,
  Building2,
  Newspaper,
  Users,
  FileSignature,
  Puzzle,
  Save,
  Settings2,
  ChevronRight,
  Circle,
  Square,
  RectangleHorizontal,
  Smile,
} from 'lucide-angular';

@NgModule({
  imports: [
    LucideAngularModule.pick({
      Mail,
      Phone,
      MapPin,
      Globe,
      Download,
      Trash2,
      Link,
      Camera,
      Bold,
      Italic,
      Underline,
      ListOrdered,
      List,
      TextAlignStart,
      TextAlignCenter,
      TextAlignEnd,
      TextAlignJustify,
      RemoveFormatting,
      House,
      ChevronUp,
      ChevronDown,
      Sparkles,
      CircleUser,
      CreditCard,
      Bell,
      LogOut,
      UserKey,
      LogIn,
      GripVertical,
      Eye,
      X,
      Pencil,
      EllipsisVertical,
      ArrowRight,
      Copy,
      Files,
      FileText,
      GraduationCap,
      Briefcase,
      FolderOpen,
      Award,
      Languages,
      Heart,
      BookOpen,
      Trophy,
      Building2,
      Newspaper,
      Users,
      FileSignature,
      Puzzle,
      Save,
      Settings2,
      ChevronRight,
      Circle,
      Square,
      RectangleHorizontal,
      Smile,
    }),
  ],
  exports: [LucideAngularModule],
})
export class LucideIconModule {}

export { LucideAngularModule };
