// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeBuilder.Persistence.Context;

#nullable disable

namespace ResumeBuilder.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808143025_Add-P-Settings")]
    partial class AddPSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.CertificateEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CertificateGridColumn")
                        .HasColumnType("integer");

                    b.Property<string>("CertificateLayout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CertificateRowSpacing")
                        .HasColumnType("text");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStartRowsWithBullet")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubinfoStyle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("CertificateEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.EducationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsByOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchoolName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("EducationEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsByOrder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("ExperienceEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.LanguageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStartRowsWithBullet")
                        .HasColumnType("boolean");

                    b.Property<int?>("LanguageGridColumn")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageLayout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LanguageName")
                        .HasColumnType("text");

                    b.Property<string>("LanguageRowSpacing")
                        .HasColumnType("text");

                    b.Property<string>("Proficiency")
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubinfoStyle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("LanguageEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ObjectiveEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("ObjectiveEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.PersonalInformationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GitHub")
                        .HasColumnType("text");

                    b.Property<bool>("IsTitleProfessionalTitleOnSameLine")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text");

                    b.Property<string>("PersonalInformationIconStyle")
                        .HasColumnType("text");

                    b.Property<string>("PersonalInformationLayout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PersonalInformationMarkerStyle")
                        .HasColumnType("text");

                    b.Property<string>("PersonalInformationTextAlignment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProfessionalTitle")
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("PersonalInformationEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ProjectEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("ProjectEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.SkillEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsStartRowsWithBullet")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SkillGridColumn")
                        .HasColumnType("integer");

                    b.Property<string>("SkillLayout")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .HasColumnType("text");

                    b.Property<string>("SkillRowSpacing")
                        .HasColumnType("text");

                    b.Property<string>("SubinfoStyle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("SkillEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.SummaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResumeSectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResumeSectionId");

                    b.ToTable("SummaryEntry", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resume", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("ResumeSection", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.ResumeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColorHeader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("FontSize")
                        .HasColumnType("real");

                    b.Property<bool>("IsPagenNumbersEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LeftRightMargin")
                        .HasColumnType("integer");

                    b.Property<float>("LineHeight")
                        .HasColumnType("real");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionTitleColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("SectionTitleFontSize")
                        .HasColumnType("real");

                    b.Property<int>("SpaceBetweenElements")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId")
                        .IsUnique();

                    b.ToTable("ResumeSetting", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.CertificateEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("CertificateEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.EducationEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("EducationEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ExperienceEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("ExperienceEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.LanguageEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("LanguageEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ObjectiveEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("ObjectiveEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.PersonalInformationEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("PersonalInformationEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.ProjectEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("ProjectEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.SkillEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("SkillEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Entries.SummaryEntry", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", "ResumeSection")
                        .WithMany("SummaryEntries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeSection");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Resume", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Identity.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.Resume", "Resume")
                        .WithMany("ResumeSections")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.ResumeSetting", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resumes.Resume", "Resume")
                        .WithOne("Settings")
                        .HasForeignKey("ResumeBuilder.Domain.Entities.Resumes.ResumeSetting", "ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.Resume", b =>
                {
                    b.Navigation("ResumeSections");

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resumes.ResumeSection", b =>
                {
                    b.Navigation("CertificateEntries");

                    b.Navigation("EducationEntries");

                    b.Navigation("ExperienceEntries");

                    b.Navigation("LanguageEntries");

                    b.Navigation("ObjectiveEntries");

                    b.Navigation("PersonalInformationEntries");

                    b.Navigation("ProjectEntries");

                    b.Navigation("SkillEntries");

                    b.Navigation("SummaryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
